name: Docker cron

on:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build-cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
    - name: Login to DockerHub Registry
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker buildx build --push --tag flavienperier/dns:cron-$GITHUB_JOB --platform linux/amd64,linux/arm/v7,linux/arm64/v8 .

  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
    - name: Login to DockerHub Registry
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the latest Docker image
      run: docker buildx build --push --tag flavienperier/dns:latest --platform linux/amd64,linux/arm/v7,linux/arm64/v8 .
